apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bj9kec6ui-nodejs
  janus-idp.io/tekton: bj9kec6ui-nodejs
  backstage.io/kubernetes-id: bj9kec6ui-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bj9kec6ui-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
